#!/usr/bin/python3

import multiprocessing
import os
import re
import subprocess
import sys
import util

HOME = os.path.expanduser("~")
TEST_USER_PROFILE_PATH = os.path.join(HOME, "tmp", "test-chromium")

from optparse import OptionParser

# Options

parser = OptionParser()
parser.add_option("-v", "--verbose", dest="verbose",
                  action="store_true",
                  help="show verbose messages")
parser.add_option("-d", "--dryrun", dest="dryrun",
                  action="store_true",
                  help="dry run, log what we plan to do but don't actually do anything")
parser.add_option("-t", "--tests_only", dest="testsonly",
                  action="store_true",
                  help="Only build unit tests")

(options, args) = parser.parse_args()

os.chdir(os.path.join(HOME, "chromium", "src"))
cmd = "gn gen out/Default --args='" + " ".join(util.common_gn_args()) + "'"
util.run(cmd, "Preparing for build...", options)

# TODO: Run goma if it's not running.
if not util.is_process_running("compiler_proxy"):
  util.show_goma_warning()
if options.testsonly:
  target = "unit_tests"
else:
  target = "chrome unit_tests"
cmd = ("autoninja -C out/Default " + target)
status_code = util.run(cmd, "Compiling, this may take a while...", options)
if status_code == 0:
  print("All done.")
else:
  print("Compilation failed. Please use '-v' to see actual failures.")
sys.exit(status_code)
