#!/usr/bin/python

import multiprocessing
import os
import re
import subprocess
import sys
import util

HOME = os.path.expanduser("~")
TEST_USER_PROFILE_PATH = os.path.join(HOME, "tmp", "test-chromium")

from optparse import OptionParser

# Options

parser = OptionParser()
parser.add_option("-v", "--verbose", dest="verbose",
                  action="store_true",
                  help="show verbose messages")
parser.add_option("-d", "--dryrun", dest="dryrun",
                  action="store_true",
                  help="dry run, log what we plan to do but don't actually do anything")

(options, args) = parser.parse_args()

os.chdir(os.path.join(HOME, "chromium", "src"))
cmd = "gn gen out/Default --args='" + " ".join(util.common_gn_args()) + "'"
if options.verbose:
  print("Running '" + cmd + "'...")
else:
  print("Preparing for build...")
if not options.dryrun:
  os.system(cmd)

# TODO: Run goma if it's not running.
if not util.is_process_running("compiler_proxy"):
  util.show_goma_warning()
cmd = ("autoninja -C out/Default chrome unit_tests")
if options.verbose:
  print("Running '" + cmd + "'...")
else:
  print("Compiling, this might take a while...")
status_code = 0
if not options.dryrun:
  status_code = util.system_silent(cmd, options)
if status_code == 0:
  print("All done.")
else:
  print("Compilation failed. Please use '-v' to see actual failures.")
sys.exit(status_code)
