#!/usr/bin/python3

import os

print("Work in progress!")


os.system("wget -O stats.html "
          "\"https://chromium-review.googlesource.com/changes/"
          "?O=81&S=0&n=100&q=status:merged+owner:manucornet@chromium.org"
          "+branch:master\"")

