#!/usr/bin/python3

import os
import sys
import crutil

file = sys.argv[1] if len(sys.argv) > 1 else None

branch = crutil.get_current_branch()

os.system("git diff origin " + branch + (" -- " + file if file else ""))
