#!/usr/bin/python3

import os
import sys
import util

file = sys.argv[1] if len(sys.argv) > 1 else None

branch = util.get_current_branch()

os.system("git diff origin " + branch + (" -- " + file if file else ""))
