#!/usr/bin/python3

import os
import sys
import util

if len(sys.argv) < 2:
  print("I need a CL number as an argument. Thanks!")
  sys.exit(1)

cl = int(sys.argv[1])

if len(sys.argv) > 2:
  editor = sys.argv[2]
else:
  editor = os.getenv("EDITOR").strip()
  if editor == "":
    print("No editor was specified and $EDITOR is empty, bailing out.")
    sys.exit(1)
  print("No editor specified, using '" + editor + "' = $EDITOR")

home = os.path.expanduser("~")
cr_dir = os.path.join(home, "chromium", "src")
os.chdir(cr_dir)
files_to_edit = " ".join(util.get_open_files_for_cl(cl))
command = editor + " " + files_to_edit
if editor in ['gedit', 'qtcreator']:
  command += "&"
print(command)
os.system(command)
