#!/usr/bin/python3

import os
import sys
import crutil

editor = sys.argv[1] if len(sys.argv) > 1 else ""

cl = crutil.get_issue_number()
if cl:
    os.system("creditopenfilesincl " + cl + " " + editor)
