#!/usr/bin/python3

import os
import util

from optparse import OptionParser

(options, args) = util.get_options_and_args()

os.chdir(util.get_chromium_src_dir())

print("Generating IDE project...")
os.system(
    "gn gen  "
    + util.get_out_dir()
    + "  --ide=qtcreator  --args='"
    + " \
    ".join(
        util.common_gn_args()
    )
    + "'"
)
