#!/usr/bin/python3

import os
import crutil

from optparse import OptionParser

(options, args) = crutil.get_options_and_args()

os.chdir(crutil.get_chromium_src_dir())

print("Generating IDE project...")
os.system(
    "gn gen  "
    + crutil.get_out_dir()
    + "  --ide=qtcreator  --args='"
    + " \
    ".join(
        crutil.common_gn_args()
    )
    + "'"
)
