#!/usr/bin/python3

import getpass
import os
import shlex
import subprocess
import crutil

running = subprocess.check_output(shlex.split("ps aux")).decode()
username = getpass.getuser()
pattern = "compiler_proxy"

proc_to_kill = []
proc_cant_kill = []
for l in running.split("\n"):
    if pattern in l:
        # The username is sometimes truncated in the ps output.
        if l.startswith(username[:5]):
            proc_to_kill.append(l)
        else:
            proc_cant_kill.append(l)

if len(proc_to_kill):
    print(crutil.COLOR_FORMAT_GREEN_STRING.format("Goma is running"))
else:
    print(crutil.COLOR_FORMAT_YELLOW_STRING.format("Goma is NOT running"))
