#!/usr/bin/python3

import os
import sys
import crutil

goma_dir = crutil.get_goma_dir()

if os.path.exists(goma_dir):
    print(goma_dir + " already exists. Please remove it if you'd like to reinstall.")
    sys.exit(0)

os.system("cipd install infra/goma/client/linux-amd64 -root " + goma_dir)

print("Logging in...")
os.system(os.path.join(goma_dir, "goma_auth.py") + " login")
