#!/usr/bin/python

import multiprocessing
import os
import re
import subprocess
import sys
import util

HOME = os.path.expanduser("~")
TEST_USER_PROFILE_PATH = os.path.join(HOME, "tmp", "test-chromium")
GN_ARGS = [
  "enable_nacl = false",
]

options = {}

os.chdir(os.path.join(HOME, "chromium", "src"))

cmd = "gn gen out/Default --args='" + " ".join(GN_ARGS) + "'"
util.run(cmd, "Preparing to build...", options)

# TODO: Run goma if it's not running.
if not util.is_process_running("compiler_proxy"):
  util.show_goma_warning()

cmd = ("autoninja -C out/Default -j" + str(n_jobs) + " chrome")
status_code = util.run(cmd, "Compiling, this may take a while...", options)
if status_code != 0:
  print("Compilation failed, aborting.")
  sys.exit(status_code)

#TODO: Make those configurable
os.system("./out/Default/chrome --user-data-dir=" + TEST_USER_PROFILE_PATH)
