#!/usr/bin/python

import os
import re
import subprocess
import sys

def is_process_running(process):
  s = subprocess.Popen(["ps", "axw"], stdout=subprocess.PIPE)
  for x in s.stdout:
    if re.search(process, x.decode()):
      return True
    return False

# TODO: hide compilation output, provide verbose flag.

home = os.path.expanduser("~")

GOMA_DIR = os.path.join(home, "goma")
GN_ARGS = ("target_os = \"chromeos\""
          "is_component_build = true "
          "enable_nacl = false "
          "use_goma = true "
          "goma_dir=\"" + GOMA_DIR  + "\"")
print("Running gn gen...")
os.system("gn gen out_cros/Release --args='" + GN_ARGS + "'")

# TODO: Run goma if it's not running.
if not is_process_running("compiler_proxy"):
  print("Warning: goma is not running, the build will be slower")
print("Compiling, this might take a while...")
os.system("ninja -C out_cros/Release -j1000 chrome chrome_sandbox")
