#!/usr/bin/python

import os
import socket
import sys
import util

from optparse import OptionParser

DEPOT_TOOLS = "depot_tools"
TRY_VERBOSE_MESSAGE = ("Please try calling me again with the verbose (-v) "
                       "option to see what's going on.")

# Options

parser = OptionParser()
parser.add_option("-f", "--full-history", dest="history",
                  action="store_true",
                  help="Download the full repo history (longer fetch)")
parser.add_option("-v", "--verbose", dest="verbose",
                  action="store_true",
                  help="Show verbose messages")
parser.add_option("-d", "--dryrun", dest="dryrun",
                  action="store_true",
                  help="dry run, log what we plan to do but don't actually do anything")

# Base variables

(options, args) = parser.parse_args()
HOME = os.path.expanduser("~")
BASE_DIR = os.path.join(HOME, "chromium")
dir_name = ""

if not util.is_online():
  print("You seem to be offline. I won't be able to do much. Aborting.")
  sys.exit(1)

os.chdir(HOME)

# Fetch depot_tools

if os.path.exists(DEPOT_TOOLS):
  print(DEPOT_TOOLS + " is already checked out, updating it...")
  os.chdir(DEPOT_TOOLS)
  os.system("git pull")
  os.chdir("..")
else:
  print("Fetching " + DEPOT_TOOLS + "...")
  util.system_silent("git clone "
                     "https://chromium.googlesource.com/chromium/tools/depot_tools.git",
                     options)

if not os.path.exists(DEPOT_TOOLS):
  print("I wasn't able to fetch the depot tools. Aborting. Potential fix: delete your ~/.gitcookies")
  if not options.verbose:
    print(TRY_VERBOSE_MESSAGE)
  sys.exit(1)

# Create base directory

if not os.path.exists(BASE_DIR):
  os.mkdir(BASE_DIR)

# Print info about PATH

shell = os.environ['SHELL'].rsplit('/', 1) [-1]
rc_file = os.path.join(HOME, "." + shell + "rc")
rc_file_contents = open(rc_file, "r").read()
if "depot_tools" not in rc_file_contents:
  print("We recommend adding this line to your file '" + rc_file + "':\n\n\t"
        "export PATH=$PATH:" + os.path.join(HOME, "depot_tools") + "\n")

# Fetch the source code

os.chdir(BASE_DIR)

if os.path.exists(".gclient") and not os.path.exists("src"):
  print("I see remnants of a checkout attempt, but not checkout. " + \
      "I am going to delete the .gclient directory.")
  os.system("rm -rf .gclient")

if os.path.exists("src"):
  print("Code seems already checked out, skipping that part.")
else:
  print("Fetching the source code. This will take a while...")
  flags = ["--nohooks"]
  if not options.history:
    flags.append("--no-history")
  fetch_command = "" + os.path.join(HOME, DEPOT_TOOLS, "fetch") + " " + \
      " ".join(flags) + " " + "chromium"
  if options.verbose:
    print(fetch_command)
  util.system_silent(fetch_command, options)

if not os.path.exists("src"):
  print("Fetching the code has failed, aborting. Sorry about that. ")
  if not options.verbose:
    print(TRY_VERBOSE_MESSAGE)
  sys.exit(1)

util.ensure_goma_installed()

# Run the hooks

os.chdir(BASE_DIR)
os.chdir("src")
print("Installing build dependencies... I may need your sudo password.")
util.system_silent("build/install-build-deps.sh --no-prompt", options)
print("Running the hooks...")
util.system_silent("gclient runhooks", options)

# Build

print("Doing the first build...")
sc = util.system_silent("gn gen out/Default", options)
if sc != 0:
  print("gn step failed, aborting.")
  sys.exit(sc)

# TODO: Run goma if it's not running.
if not util.is_process_running("compiler_proxy"):
  util.show_goma_warning()
util.system_silent("autoninja -C out/Default chrome", options)
# TODO: Catch Ctrl-C, abort cleanly.	
if sc != 0:
  print("Compilation failed, aborting.")
  sys.exit(sc)

# The end

print("\nAll done! Your Chromium directory is " + BASE_DIR)
