#!/usr/bin/python

import os
import socket
import sys
import util

from optparse import OptionParser

BASE_DIR = "chromium"
DEPOT_TOOLS = "depot_tools"
TRY_VERBOSE_MESSAGE = ("Please try calling me again with the verbose (-v) "
                       "option to see what's going on.")

# Options

parser = OptionParser()
parser.add_option("-v", "--verbose", dest="verbose",
                  action="store_true",
                  help="Show verbose messages")
parser.add_option("-d", "--dryrun", dest="dryrun",
                  action="store_true",
                  help="dry run, log what we plan to do but don't actually do anything")

# Base variables

(options, args) = parser.parse_args()
home = os.path.expanduser("~")
dir_name = ""

os.system("sudo apt-get install qtcreator")

os.chdir(os.path.join(home, BASE_DIR, "src"))

print("Generating IDE project...")
os.system("gn gen out/Release --ide=qtcreator")

# Build

print("Doing the first build...")
sc = util.system_silent("gn gen out/Default", options)
if sc != 0:
  print("gn step failed, aborting.")
  sys.exit(sc)

# The end

#print("\nAll done! Your Chromium directory is " + os.path.join(home, BASE_DIR))
