#!/usr/bin/python3

import os
import util
import sys

from optparse import OptionParser

parser = OptionParser()
(options, args) = util.get_options_and_args(parser)

if len(args) == 0:
  print("Please pass in the name of a board. Some examples: " + ", ".join(["gru"]))
  sys.exit(1)

board = args[0]

# Base variables

HOME = os.path.expanduser("~")
BASE_DIR = os.path.join(HOME, "chromiumos")

if not util.is_online():
  print("You seem to be offline. I won't be able to do much. Aborting.")
  sys.exit(1)

print("Installing some dependencies...")
os.system("sudo apt -y install lvm2 thin-provisioning-tools")

os.chdir(HOME)

fetched = util.ensure_depot_tools(options)
if not fetched:
  if not options.verbose:
    print(TRY_VERBOSE_MESSAGE)
  sys.exit(1)

# Create base directory

if not os.path.exists(BASE_DIR):
  os.mkdir(BASE_DIR)

# Fetch the source code

os.chdir(BASE_DIR)

if os.path.exists("AUTHORS"):
  print("Source code seems to already be there, skipping.")
else:
  os.system("~/depot_tools/repo init -u "
            "https://chromium.googlesource.com/chromiumos/manifest.git --repo-url "
            "https://chromium.googlesource.com/external/repo.git")
os.system("repo sync -j4")

os.system("cros_sdk -- ./setup_board --board=" + board)

#os.system("cros_sdk -- ./set_shared_user_password.sh")

os.system("cros_sdk -- ./build_packages --board=" + board + " --accept_licenses='*'")

os.system("cros_sdk -- ./build_image --board=" + board + " --noenable_rootfs_verification test")

print("If you'd like to create a USD stick, "
      "run 'cd ~/chromiumos && cros_sdk' and follow the instructions above.")
