#!/usr/bin/python3

import os
import util

from optparse import OptionParser

parser = OptionParser()
(options, args) = util.get_options_and_args(parser)

# Base variables

HOME = os.path.expanduser("~")
BASE_DIR = os.path.join(HOME, "chromiumos")

if not util.is_online():
  print("You seem to be offline. I won't be able to do much. Aborting.")
  sys.exit(1)

print("Installing some dependencies...")
os.system("sudo apt -y install lvm2 thin-provisioning-tools")

os.chdir(HOME)

fetched = util.ensure_depot_tools(options)
if not fetched:
  if not options.verbose:
    print(TRY_VERBOSE_MESSAGE)
  sys.exit(1)

# Create base directory

if not os.path.exists(BASE_DIR):
  os.mkdir(BASE_DIR)

# Fetch the source code

os.chdir(BASE_DIR)

if os.path.exists("AUTHORS"):
  print("Source code seems to already be there, skipping.")
else:
  os.system("~/depot_tools/repo init -u "
            "https://chromium.googlesource.com/chromiumos/manifest.git --repo-url "
            "https://chromium.googlesource.com/external/repo.git")
  os.system("repo sync -j4")

print("Done. Now please run these commands:\n\t" + \
    " \\\n\t".join(["cd ~/chromiumos", "cros_sdk"]))
