#!/usr/bin/python3

import os
import crutil
import sys

from optparse import OptionParser

parser = OptionParser()
(options, args) = crutil.get_options_and_args(parser)

if len(args) == 0:
    print(
        "Please pass in the name of a board. Some examples: "
        + ", ".join(["gru", "kukui", "nocturne"])
    )
    sys.exit(1)

board = args[0]

# Base variables

HOME = os.path.expanduser("~")
BASE_DIR = os.path.join(HOME, "chromiumos")

if not crutil.is_online():
    print("You seem to be offline. I won't be able to do much. Aborting.")
    sys.exit(1)

# TODO: Use the apt module to check if these are already installed.
print("Installing some dependencies...")
os.system("sudo apt -y install lvm2 thin-provisioning-tools")

os.chdir(HOME)

fetched = crutil.ensure_depot_tools(options)
if not fetched:
    if not options.verbose:
        print(TRY_VERBOSE_MESSAGE)
    sys.exit(1)

# Create base directory

if not os.path.exists(BASE_DIR):
    os.mkdir(BASE_DIR)

# Fetch the source code

os.chdir(BASE_DIR)

if os.path.exists("AUTHORS"):
    print("Source code seems to already be there, skipping.")
else:
    print("Getting source code...")
    os.system(
        "~/depot_tools/repo init -u "
        "https://chromium.googlesource.com/chromiumos/manifest.git --repo-url "
        "https://chromium.googlesource.com/external/repo.git"
    )
print("Syncing source code...")
os.system("repo sync -j" + str(crutil.get_job_count()))

print("Setting up the '" + board + "'board...")
os.system("cros_sdk -- ../../chromite/bin/setup_board --board=" + board)

# os.system("cros_sdk -- ./set_shared_user_password.sh")

print("Building packages...")
os.system("cros_sdk -- ./build_packages --board=" + board + " --accept_licenses='*'")

print("Building image...")
os.system(
    "cros_sdk -- ./build_image --board="
    + board
    + " --noenable_rootfs_verification test"
)

print(
    "If you'd like to create a USB stick, "
    "run 'cd ~/chromiumos && cros_sdk' and follow the instructions above."
)
