#!/usr/bin/python3

import os
import socket
import sys
import util

from optparse import OptionParser

BASE_DIR = "chromium"
DEPOT_TOOLS = "depot_tools"
TRY_VERBOSE_MESSAGE = ("Please try calling me again with the verbose (-v) "
                       "option to see what's going on.")

(options, args) = util.get_options_and_args()
home = os.path.expanduser("~")
dir_name = ""

os.system("sudo apt-get install qtcreator")

os.chdir(os.path.join(home, BASE_DIR, "src"))

print("Generating IDE project...")
os.system("gn gen out/Default --ide=qtcreator  --args='" + " 
".join(util.common_gn_args()) + "'")
