#!/usr/bin/python3

import os
import crutil

from optparse import OptionParser

(options, args) = crutil.get_options_and_args()

os.system("sudo apt-get install qtcreator")

os.chdir(crutil.get_chromium_src_dir())
os.system("crgenide")
