#!/usr/bin/python3

import os
import sys
import crutil

(options, args) = crutil.get_options_and_args()

os.chdir(crutil.get_chromium_src_dir())

print("Looking for local changes in all git repositories...")
crutil.check_for_local_changes_in_all_repos()
