#!/usr/bin/python3

import os
import sys

if len(sys.argv) < 2:
  print("I need a full commit hash as an argument")
  sys.exit(1)
commit = sys.argv[1]
# TODO: Sanity-check the input

print("Resetting git workspace to commit " + commit + "...")
os.system("git reset --hard " + commit)
print("Running gclient to sync all the right things...")
# -D deletes stuff that's no longer (or not yet) part of the repos.
os.system("gclient sync -D -r src@HEAD")
print("All done.")
