#!/usr/bin/python3

import os
import sys
import util

if util.is_google_machine():
  os.system("glogin")

(options, args) = util.get_options_and_args()

os.chdir(util.get_chromium_src_dir())

if util.get_current_branch() != "master":
  print("Switching to 'master' before updating... "
        "Please run 'crupdateallbranches' to update everything.")
  os.system("git checkout master")

util.run("git rebase-update && gclient sync", "Updating...", options)
