#!/usr/bin/python3

import os
import util
import subprocess
import sys

os.chdir(util.get_chromium_src_dir())
child = subprocess.Popen(["git", "diff", "--exit-code", "--quiet"])
streamdata = child.communicate()[0]
rc = child.returncode

if rc != 0:
  print("Please commit pending changes first.")
  sys.exit(1)

print("Formatting...")
os.system("git cl format")

child = subprocess.Popen(["git", "diff", "--exit-code", "--quiet"])
streamdata = child.communicate()[0]
rc = child.returncode

if rc != 0:
  print("Committing format changes...")
  os.system("git commit --all --amend --no-edit")

print("Uploading...")
# Bypass questions
os.system("git cl upload --force")
