#!/usr/bin/python3

import os
import util
import sys

os.system(os.path.join(util.get_crscripts_dir(), "crupdate"))

print("Now merging the updated code with all branches...")

os.chdir(util.get_chromium_src_dir())
for b in util.get_branches():
  print(b + "...")
  os.system("git checkout " + b)
  os.system("git merge origin/master --no-edit")

os.system("git checkout master")

if util.get_current_branch() != "master":
  print("There were some merge issues, please resolve them and try again")
  sys.exit(1)
